all: blogging

blogging: go_array_loop_with_range go_array_copy

go_array_loop_with_range:
	go build -o go_array_loop_with_range go_array_loop_with_range.go

go_array_copy:
	go build -o go_array_copy go_array_copy.go
