all: blogging

blogging: go_pointer_basics go_cycle_reference go_memmap

go_pointer_basics:
	go build -o go_pointer_basics go_pointer_basics.go

go_cycle_reference:
	go build -o go_cycle_reference go_cycle_reference.go

go_memmap:
	go build -o go_memmap go_memmap.go