all: blogging

blogging: go_pointer_basics go_cycle_reference go_mem_layout_struct go_mem_layout_int

go_pointer_basics:
	go build -o go_pointer_basics go_pointer_basics.go

go_cycle_reference:
	go build -o go_cycle_reference go_cycle_reference.go

go_mem_layout_struct:
	go build -o go_mem_layout_struct go_mem_layout_struct.go

go_mem_layout_int:
	go build -o go_mem_layout_int go_mem_layout_int.go
