all: blogging

blogging: go_anonymous_struct go_struct_in_struct go_embedded_struct go_struct_padding

go_anonymous_struct:
	go build -o go_anonymous_struct go_anonymous_struct.go

go_struct_in_struct:
	go build -o go_struct_in_struct go_struct_in_struct.go

go_embedded_struct:
	go build -o go_embedded_struct go_embedded_struct.go

go_struct_padding:
	go build -o go_struct_padding go_struct_padding.go
