all: blogging

blogging: go_switch_fallthrough go_switch_case_cond

go_switch_fallthrough:
	go build -o go_switch_fallthrough go_switch_fallthrough.go

go_switch_case_cond:
	go build -o go_switch_case_cond go_switch_case_cond.go
