all: blogging

blogging: go_func_divide go_func_divide_by_zero

go_func_divide:
	go build -o go_func_divide go_func_divide.go

go_func_divide_by_zero:
	go build -o go_func_divide_by_zero go_func_divide_by_zero.go
