all: blogging

blogging: go_string_traversal_index go_string_traversal_rune_array go_string_traversal_range \
	go_string_operators \
	go_string_internals

go_string_traversal_index:
	go build -o go_string_traversal_index go_string_traversal_index.go

go_string_traversal_rune_array:
	go build -o go_string_traversal_rune_array go_string_traversal_rune_array.go

go_string_traversal_range:
	go build -o go_string_traversal_range go_string_traversal_range.go

go_string_operators:
	go build -o go_string_operators go_string_operators.go

go_string_internals:
	go build -o go_string_internals go_string_internals.go
